import Link from "next/link";
import { surfaceClass } from "@/components/imperial-surface";
import { DigitalInstrument } from "@/components/digital-instrument";
import { DigitalWorldSelector, AetheliosPreview } from "@/components/digital-reserve";
import { PublicDirector } from "@/components/public-reserve";
import { PublicCollection } from "@/components/public-worlds";
import "./public-reserve.css";
import "./public-worlds.css";
export const metadata = {
  title: "Your personal digital ecosystem",
  description: "Legacy Reserve connects your presence, performance and wellbeing. Explore personal routines, Vitalis, Aethelios and a standard that travels with you.",
};
export default function Discover() {
  return <main id="main" className="digital-reserve public-reserve">
    <PublicDirector />
    <section className="digital-arrival public-scene" data-public-scene aria-labelledby="digital-arrival-title">
      <div className="digital-arrival-field" aria-hidden="true"><DigitalInstrument /><div className="digital-horizon" /></div>
      <div className="digital-arrival-copy"><p className="digital-label">LEGACY RESERVE / YOUR PERSONAL DIGITAL ECOSYSTEM</p><h1 id="digital-arrival-title">Your life.<br /><em>At a higher standard.</em></h1><p>Presence. Performance. Wellbeing. A personal environment for the routines you keep, the direction you choose, and the life you’re building.</p><div className="digital-actions"><a href="#pathways" className="button button-gold">Explore your Reserve ↗</a><Link href="/signin?next=/home" className="text-link">Open your personal Reserve ↗</Link></div><span className="digital-arrival-note">DIGITAL FIRST. WITH YOU, WHEREVER YOU ARE.</span></div>
      <nav className={surfaceClass("glass", "digital-arrival-console")} aria-label="Inside your digital Reserve"><span className="digital-label">FIVE WORLDS / ONE RESERVE</span><Link href="/pathways"><b>01</b><span><strong>Reserve</strong><small>Presence & Performance routines</small></span><i aria-hidden="true">↗</i></Link><Link href="/vitalis"><b>02</b><span><strong>Vitalis</strong><small>Legacy Reserve Vitalis</small></span><i aria-hidden="true">↗</i></Link><Link href="/discover/aethelios"><b>03</b><span><strong>Aethelios</strong><small>Aethelios concierge</small></span><i aria-hidden="true">↗</i></Link><Link href="/visit"><b>04</b><span><strong>Sanctum</strong><small>Physical locations & appointments</small></span><i aria-hidden="true">↗</i></Link><Link href="/shop"><b>05</b><span><strong>Collection</strong><small>Luxury products & daily rituals</small></span><i aria-hidden="true">↗</i></Link></nav>
      <div className="digital-arrival-axis" aria-hidden="true"><span>PRESENCE</span><i/><span>PERFORMANCE</span><i/><span>VITALIS</span></div>
    </section>
    <nav className="digital-chapters" aria-label="Digital ecosystem chapters"><a href="#pathways">Your direction</a><a href="#vitalis">Vitalis</a><a href="#intelligence">Aethelios</a><a href="#the-collection">Collection</a><a href="#sanctum">Sanctum</a></nav>
    <section id="pathways" className="digital-pathways digital-section" aria-labelledby="digital-pathways-title"><header className="digital-section-heading"><p className="digital-label">01 / THREE WORLDS. ONE PERSONAL RESERVE.</p><h2 id="digital-pathways-title">Choose what matters<br /><em>to you today.</em></h2><p>Explore the experience. Change your direction. See where it takes you.</p></header><DigitalWorldSelector /><div className="digital-continuity"><span>CHOOSE A DIRECTION</span><i aria-hidden="true">→</i><span>BUILD YOUR RHYTHM</span><i aria-hidden="true">→</i><span>RETURN TO YOUR RESERVE</span></div></section>
    <section id="vitalis" className="digital-vitalis digital-section public-scene" data-public-scene aria-labelledby="digital-vitalis-title"><div className="digital-vitalis-layout"><div className="digital-vitalis-object"><DigitalInstrument quiet /></div><div><p className="digital-label">02 / LEGACY RESERVE VITALIS</p><span className="digital-availability"><i/> FREE WELLNESS PILOT AVAILABLE</span><h2 id="digital-vitalis-title">Wellbeing.<br /><em>With a longer view.</em></h2><p>Your private wellness world. Begin with sleep consistency, everyday movement or meal preparation. Set a weekly target. Keep a rhythm worth returning to.</p><div className="digital-actions"><Link href="/vitalis/journey" className="button button-gold">Start your free wellness rhythm ↗</Link><Link href="/vitalis" className="text-link">Discover the Vitalis vision ↗</Link></div></div></div><div className="digital-next-horizon"><span>THE NEXT HORIZON / PLANNED</span><p>Health intelligence. Longitudinal insights. Qualified clinical connections.</p><Link href="/vitalis#early-access">Explore what’s ahead ↗</Link></div></section>
    <section id="intelligence" className="digital-intelligence digital-section" aria-labelledby="digital-intelligence-title"><div className="digital-section-heading"><p className="digital-label">03 / AETHELIOS. YOUR CONCIERGE.</p><h2 id="digital-intelligence-title">Less searching.<br /><em>A clearer next step.</em></h2><p>Connect your direction with the right Reserve tools. Aethelios helps you navigate routines, verified membership benefits and your next action.</p><Link href="/discover/aethelios" className="text-link">Meet your digital concierge ↗</Link></div><AetheliosPreview /></section>
    <PublicCollection />
    <section id="sanctum" className="digital-sanctum digital-section" aria-labelledby="digital-sanctum-title"><div><p className="digital-label">05 / SANCTUM. THE PHYSICAL WORLD.</p><h2 id="digital-sanctum-title">A digital Reserve.<br /><em>A human connection.</em></h2><p>Your Reserve begins wherever you are. When you want a visit, Sanctum connects you with the houses, people and craft within the ecosystem.</p><Link href="/visit" className="text-link">Explore Sanctum destinations ↗</Link></div><div className="digital-house-links"><Link href="/fix-it-shop"><span>KATIE GUIDRY / BLUE & GOLD</span><strong>Fix It Shop</strong><p>Men’s salon care. A personal connection.</p><b aria-hidden="true">↗</b></Link><Link href="/founder/legacy-reserve"><span>NEIL STUTES / FOUNDER</span><strong>Legacy Reserve</strong><p>The vision behind your personal ecosystem.</p><b aria-hidden="true">↗</b></Link></div></section>
    <section className="digital-section digital-founder-entry" aria-labelledby="discover-founder-title"><div><p className="digital-label">THE FOUNDER / NEIL STUTES</p><h2 id="discover-founder-title">A standard.<br/><em>A larger vision.</em></h2><p>Founder of Legacy Reserve and Aethelios Technologies. Explore the purpose behind two distinct worlds.</p><Link href="/founder" className="text-link">Meet the Founder ↗</Link></div></section>
    <section className="digital-invitation digital-section" aria-labelledby="digital-invitation-title"><p className="digital-label">YOUR STANDARD DOESN’T NEED AN ADDRESS.</p><h2 id="digital-invitation-title">Make it<br /><em>your Reserve.</em></h2><p>Start with your personal direction. Keep your routines close. Explore a membership built around the life you’re building.</p><div className="digital-actions"><Link href="/signin?next=/home" className="button button-gold">Create or access your Reserve ↗</Link><Link href="/discover/membership" className="text-link">Explore digital membership ↗</Link></div><small>Personal routines and the free Vitalis pilot are available. Paid membership is in preparation.</small></section>
    <footer className="digital-footer"><span>LEGACY RESERVE / PRESENCE. PERFORMANCE. WELLBEING.</span><Link href="/enter">Your account ↗</Link><Link href="/discover/membership">Membership ↗</Link><Link href="/visit">Sanctum ↗</Link></footer>
  </main>;
}
