import Link from "next/link";
import { DigitalInstrument } from "@/components/digital-instrument";
export const metadata = { title: "Digital membership", description: "Your digital Legacy Reserve: personal direction, routines, Vitalis and Aethelios, wherever you are." };
export default function Page() {
  return <main id="main" className="digital-reserve digital-membership">
    <section className="digital-membership-arrival digital-section"><div><p className="digital-label">LEGACY RESERVE / DIGITAL MEMBERSHIP</p><h1>Your standard.<br /><em>Wherever life takes you.</em></h1><p>A personal digital ecosystem for your presence, performance and wellbeing. Your Reserve is useful from home, on the move and between everything else.</p><div className="digital-actions"><Link href="/signin?next=/home" className="button button-gold">Create or access your Reserve ↗</Link><Link href="/home?explore=1" className="text-link">Preview the member environment ↗</Link></div><small>PERSONAL TOOLS AVAILABLE / PAID MEMBERSHIP IN PREPARATION</small></div><DigitalInstrument world="presence" /></section>
    <section className="digital-section"><header className="digital-section-heading"><p className="digital-label">THE VALUE STARTS WITH YOUR EVERYDAY LIFE.</p><h2>A direction.<br /><em>A rhythm. A place to return.</em></h2></header><div className="digital-membership-tools">{[
      ["01 / YOUR RESERVE", "Your next useful action.", "Keep your chosen priority and saved routine in one personal environment.", "/home?explore=1", "Preview your Reserve"],
      ["02 / PATHWAYS", "A standard you shape.", "Build and refine simple routines for Presence, Performance or wellbeing.", "/pathways", "Explore Pathways"],
      ["03 / VITALIS", "Wellbeing with continuity.", "The free pilot offers a private wellness direction, weekly target and daily check-ins.", "/vitalis", "Discover Vitalis"],
      ["04 / AETHELIOS", "A clearer next step.", "Navigate your routines, verified membership benefits and Reserve tools with your customer concierge.", "/discover/aethelios", "Meet Aethelios"],
    ].map(([index,title,copy,href,action])=><article key={index}><span className="digital-label">{index}</span><h3>{title}</h3><p>{copy}</p><Link href={href} className="text-link">{action} ↗</Link></article>)}</div></section>
    <section className="digital-membership-clarity digital-section"><p className="digital-label">BEGIN WITH WHAT IS AVAILABLE.</p><h2>Your Reserve.<br /><em>Your choice.</em></h2><p>Personal routines and the Vitalis wellness pilot are available with a customer account. Paid plans and expanded benefits are being prepared. Your account shows published offers and any membership access assigned to you.</p><p>A Sanctum visit is optional. Physical experiences, products and future clinical services have their own availability.</p><div className="digital-actions"><Link href="/membership" className="button button-gold">Check your membership account ↗</Link><Link href="/discover" className="text-link">Explore the digital ecosystem ↗</Link></div></section>
  </main>;
}
